[workspace]
members = [
  "flowy-user-data-model",
  "flowy-core-data-model",
  "flowy-collaboration",
  "lib-ot",
  "lib-ws",
  "lib-infra",
  "backend-service",
  "flowy-derive",
  "flowy-ast",
  "error-code",
]

[profile.dev]
split-debuginfo = "unpacked"
